name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - 
      name: set variables
      shell: bash
      run: |
        version=`grep -m 1 version pyproject.toml | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3`
        echo "version=$version" >> $GITHUB_ENV
        image_name=mkal/calvie
        echo "image_name=$image_name" >> $GITHUB_ENV  
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.image_name }}:latest , ${{ env.image_name }}:${{ env.version }}
          build-args: APP_VERSION=${{ env.version }}
